FROM python:3.12-slim

WORKDIR /app

COPY ui/requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["streamlit" ,"run" ,"ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]